[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_anchor = "6pXW4oA1MqYmpZYnhJAmE1YbuzXDmWdhnBCop3HbKy8U"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/wonder/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
